# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aba6c5f426e677b432bdd640af136b696e0b62339be9f2f3090ecdcea0da2b64358bb47085eab17aac04e40d6aac94df24765fd9d364353cfd805e6601587fb

test:
  secret_key_base: 55dd45942bbe91ed9fd36c7c10e74641b670b35d254cb5a4f74539af68458176aba1569a8650bffec94578513b0a89a0f7d29bca853daac7c06cf2afac0831db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
